global:
  scrape_interval: 15s
scrape_configs:
  -
    job_name: Jira8.x
    metrics_path: '/plugins/servlet/prometheus/metrics'
    scheme: https
    static_configs:
      -
        targets:
          - "<jira_instance1_hostname>"

  - job_name: Jira9.x
    metrics_path: '/plugins/servlet/prometheus/metrics'
    scheme: https
    static_configs:
      -
        targets:
          - "<jira_instance2_hostname>"